# Default initial positions for yumi's ros2_control fake system

initial_positions:
  gripper_l_joint: 0.0
  gripper_r_joint: 0.0
  yumi_joint_1_l: 0.0
  yumi_joint_1_r: -0.7851
  yumi_joint_2_l: 0.0
  yumi_joint_2_r: 0.0
  yumi_joint_3_l: 0.0
  yumi_joint_3_r: 0.0
  yumi_joint_4_l: 0.0
  yumi_joint_4_r: 0.0
  yumi_joint_5_l: 0.0
  yumi_joint_5_r: 0.0
  yumi_joint_6_l: 0.0
  yumi_joint_6_r: 0.0
  yumi_joint_7_l: 0.0
  yumi_joint_7_r: 0.0