# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - yumi_arm_left_controller
    - yumi_arm_right_controller
    - hand_left_controller
    - hand_right_controller

  yumi_arm_left_controller:
    type: FollowJointTrajectory
    joints:
      - yumi_joint_1_l
      - yumi_joint_2_l
      - yumi_joint_7_l
      - yumi_joint_3_l
      - yumi_joint_4_l
      - yumi_joint_5_l
      - yumi_joint_6_l
    action_ns: follow_joint_trajectory
    default: true
  yumi_arm_right_controller:
    type: FollowJointTrajectory
    joints:
      - yumi_joint_1_r
      - yumi_joint_2_r
      - yumi_joint_7_r
      - yumi_joint_3_r
      - yumi_joint_4_r
      - yumi_joint_5_r
      - yumi_joint_6_r
    action_ns: follow_joint_trajectory
    default: true
  hand_left_controller:
    type: GripperCommand
    joints:
      - gripper_l_joint
    action_ns: gripper_cmd
    default: true
  hand_right_controller:
    type: GripperCommand
    joints:
      - gripper_r_joint
    action_ns: gripper_cmd
    default: true