# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    yumi_arm_left_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    yumi_arm_right_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    hand_left_controller:
      type: position_controllers/GripperActionController


    hand_right_controller:
      type: position_controllers/GripperActionController


    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

yumi_arm_left_controller:
  ros__parameters:
    joints:
      - yumi_joint_1_l
      - yumi_joint_2_l
      - yumi_joint_7_l
      - yumi_joint_3_l
      - yumi_joint_4_l
      - yumi_joint_5_l
      - yumi_joint_6_l
    command_interfaces:
      - velocity
    state_interfaces:
      - position
      - velocity
    allow_nonzero_velocity_at_trajectory_end: true
yumi_arm_right_controller:
  ros__parameters:
    joints:
      - yumi_joint_1_r
      - yumi_joint_2_r
      - yumi_joint_7_r
      - yumi_joint_3_r
      - yumi_joint_4_r
      - yumi_joint_5_r
      - yumi_joint_6_r
    command_interfaces:
      - velocity
    state_interfaces:
      - position
      - velocity
    allow_nonzero_velocity_at_trajectory_end: true
hand_left_controller:
  ros__parameters:
    joint: gripper_l_joint
hand_right_controller:
  ros__parameters:
    joint: gripper_r_joint